### ISSUE TITLE
Forge 1.20.1 update sometime? 

### ISSUE THREAD

**Issue by Chimera7** [MrCrayfish/Configured#105]
Hi, would really like to use JEI on my 1.20.1 mod play through. Hope you're having a good day and that an update comes out eventually. Cheers

**Comment by Zorro8183** [comment]
same here. I just started 1.20.1 and realized I didn't have configured. please update this MrCrayfish

**Comment by Aetrnl94** [comment]
Agreed! Is there any chance that you can tell us if a 1.20.1(+) version is in-the-works (and if-so, an approximate ETA), or if you're planning on keeping only 1.19.4 updated? Thanks!!

**Comment by remplerus** [comment]
I have made an PR for 1.20.1 ( #109 ). I got Forge working but Fabric isn't working tho.

**Comment by gitguette** [comment]
> I have made an PR for 1.20.1 ( #109 ). I got Forge working but Fabric isn't working tho.

how can i build this version?

**Comment by NickoRmo** [comment]
> I have made an PR for 1.20.1 ( #109 ). I got Forge working but Fabric isn't working tho.

do you plan to release it? (same goes for ender io please)

**Comment by Xiarno** [comment]
Still waiting.

**Comment by gitguette** [comment]
the option text is invisible for me
