### ISSUE TITLE
[1.16.5-1.0.2] Configured only shows 1 of Repurposed Structures's configs

### ISSUE THREAD

**Issue by TelepathicGrunt** [MrCrayfish/Configured#11]
Hello! I am the developer for Repurposed Structures and someone pointed out that while my mod makes use of multiple config files for organization, Configured only shows the Witch Huts config which is odd. I make all the config files the same way as shown here: 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/e3b54f58ed422fc3d299cb80e0a973920c9c575c/src/main/java/com/telepathicgrunt/repurposedstructures/RepurposedStructures.java#L78-L88

Although, I do have plans in the future to move all these config files into a repurposed_structures folder within the config folder in 1.17 but I still need to figure out a good way of doing this. Is there something off with my multi-config file implementation that is breaking Configured or is this a bug within Configured?

**Comment by TelepathicGrunt** [comment]
Picture of only one config being shown
![image](https://user-images.githubusercontent.com/40846040/120899455-dbcd6180-c5fd-11eb-85a1-d39652bb3e4b.png)

**Comment by MrCrayfish** [comment]
I'll get back to you on this.

**Comment by MrCrayfish** [comment]
Thanks for bringing this up. Fixed in https://github.com/MrCrayfish/Configured/commit/3695d171a0f6bdbd25f1c55502f6879282bc794f
