### ISSUE TITLE
[1.20.1] Crash on load when using Forge 47.1.3

### ISSUE THREAD

**Issue by ffuentesm** [MrCrayfish/Configured#116]
Crash: [crash-2024-02-10_18.34.50-client.txt](https://github.com/MrCrayfish/Configured/files/14230797/crash-2024-02-10_18.34.50-client.txt)
Forge: 47.1.3
Minecraft: 1.20.1
Configured: configured-forge-1.20.1-2.2.0

When I load the game without configured, no crash happens.

**Comment by MrCrayfish** [comment]
Can you send the full log file? I got a feeling another mod is causing the issue.

**Comment by MrCrayfish** [comment]
Try updating to recommended Forge 47.2.0

**Comment by lojokey** [comment]
The same is happening to me, forge 47.2.19
[latest.log](https://github.com/MrCrayfish/Configured/files/14231739/latest.log)

**Comment by ffuentesm** [comment]
> Try updating to recommended Forge 47.2.0

Can't really move from 47.1.3, since many major mods are staying in that version for NeoForge compatibility.

**Comment by MrHimera** [comment]
@MrCrayfish 
Crashes the game on startup if the Iceberg mod is installed.

**Comment by AIRLord19** [comment]
The game crashes on version 1.20.1 forge 47.2.20. Please correct.

**Comment by MrCrayfish** [comment]
@MrHimera different issue. Open a new issue

**Comment by MrCrayfish** [comment]
@AIRLord19 Please give more details (like the crash report). Saying it just "crashes" doesn't help since when I run the game it doesn't.

**Comment by MrCrayfish** [comment]
@ffuentesm I'll look into reducing the minimum required version

**Comment by MrCrayfish** [comment]
@lojokey Downgrade to recommend. Latest has breaking changes.

**Comment by ffuentesm** [comment]
> @MrHimera different issue. Open a new issue

I do have Iceberg in my mod list as well, so that might be also a cause for the crash it?

**Comment by MrCrayfish** [comment]
> I do have Iceberg in my mod list as well, so that might be also a cause for the crash it?

Iceberg has custom integration into Configured that needs to be fixed.

**Comment by AIRLord19** [comment]
Hello, today I installed the updated mod (v2.2.2) and it’s also crashing.
Forge: 47.2.20
Minecraft: 1.20.1
Here is the file:
[crash-2024-02-12_19.35.52-client.txt](https://github.com/MrCrayfish/Configured/files/14241334/crash-2024-02-12_19.35.52-client.txt)

**Comment by ffuentesm** [comment]
I have also just updated to v2.2.2, and I tried launching with and without iceberg. It still crashes on both. 
Forge: 47.1.3
Minecraft: 1.20.1
Crash with Iceberg: [crash-2024-02-12_12.01.21-client.txt](https://github.com/MrCrayfish/Configured/files/14241545/crash-2024-02-12_12.01.21-client.txt)
Crash without Iceberg: [crash-2024-02-12_12.03.19-client.txt](https://github.com/MrCrayfish/Configured/files/14241551/crash-2024-02-12_12.03.19-client.txt)

**Comment by MrCrayfish** [comment]
@AIRLord19 The update wasn't a patch to fix the issue with Iceberg, it's on them to resolve the issue.

**Comment by dizzie1g** [comment]
FIX YOU MOD DOOD
