### ISSUE TITLE
Crash when launching on Forge 47.2 / MC version 1.20.1

### ISSUE THREAD

**Issue by robinfrt** [MrCrayfish/Configured#119]
[crash-2024-02-11_22.13.44-client.txt](https://github.com/MrCrayfish/Configured/files/14234084/crash-2024-02-11_22.13.44-client.txt)

My client crashes at launch when the mod is installed (see report attached)
MC version 1.20.1
Forge version 47.2.0

What do you think is causing it?

**Comment by robinfrt** [comment]
I saw you fixed for 1.20.4, any news on the 1.20.1 version ?

**Comment by MrCrayfish** [comment]
The report indicates you used 2.2.0, however I have since release 2.2.2

**Comment by robinfrt** [comment]
[crash-2024-02-15_22.13.55-client.txt](https://github.com/MrCrayfish/Configured/files/14302477/crash-2024-02-15_22.13.55-client.txt)

I tried with the 2.2.2 and got the same issue, I also tried removing a bunch of mods but it didn't cut it... Any suggestion?

**Comment by MrCrayfish** [comment]
I've tracked down the issue to Yung's Menu Tweaks and opened an issue on their end.

**Comment by MrCrayfish** [comment]
Can you update YUNG's Menu Tweaks to the newest version and check if the crash still occurs?

**Comment by MrCrayfish** [comment]
No need to test, just update. It should no longer crash.
