### ISSUE TITLE
[1.16.5-1.0.2] [ Suggestion] Make label for config entries show name of field if no translation exists

### ISSUE THREAD

**Issue by TelepathicGrunt** [MrCrayfish/Configured#12]
Since the in-game config hasn't existed for so long now in Forge, a lot of mods most likely do not have translations for their config names. An idea for Configured is to show the config field's name from code if the translation doesn't exist for it or just show the last part of the translation key. It will help make configs a bit more readable by default instead of the below picture. It would also really help me out as I have so many configs that it will take me way too long to create the translations for them all. Especially as I want to redo a lot of my configs and keep adding new structures to my mod.

![image](https://user-images.githubusercontent.com/40846040/120899310-14207000-c5fd-11eb-8b6c-9b3dcd0bf3df.png)

**Comment by MrCrayfish** [comment]
Patched in https://github.com/MrCrayfish/Configured/commit/633879412ca3ea4452a15df155ef1c7dbb61cc89
