### ISSUE TITLE
Forge 1.20.1. Game crashes if your try to enter to the Supplementaries mod config

### ISSUE THREAD

**Issue by IthanMendoza** [MrCrayfish/Configured#120]
The game crashes the moment you click on the config button in the mods menu.

Forge 47.2.20

[latest.log](https://github.com/MrCrayfish/Configured/files/14247580/latest.log)
[crash-2024-02-12_12.59.59-client.txt](https://github.com/MrCrayfish/Configured/files/14247599/crash-2024-02-12_12.59.59-client.txt)

**Comment by IthanMendoza** [comment]
I also posted this issue to the Supplementaries author.

**Comment by IthanMendoza** [comment]
![image](https://github.com/MrCrayfish/Configured/assets/127630637/30155f2c-44e5-4892-a01f-813873e4d36a)

**Comment by MrCrayfish** [comment]
Supplementaries has a custom integration that needs to be update. You'll need to open an issue on their repo if one doesn't exist already.

**Comment by MrCrayfish** [comment]
This has been resolved. You'll need to update moonlight lib.
