### ISSUE TITLE
fabric 1.20.4 crash when clicking

### ISSUE THREAD

**Issue by Wolf-Hydra** [MrCrayfish/Configured#121]
game crashes when clicking in the main menu. crash report attached
[crash-2024-02-12_23.11.19-client.txt](https://github.com/MrCrayfish/Configured/files/14251891/crash-2024-02-12_23.11.19-client.txt)

newer crash log with only configured, fabric api, jei, nei and mod menu instaled using standard launcher
[crash-2024-02-16_23.45.25-client.txt](https://github.com/MrCrayfish/Configured/files/14316923/crash-2024-02-16_23.45.25-client.txt)

**Comment by MrCrayfish** [comment]
Update to 2.2.3
