### ISSUE TITLE
Configured and JEI seem to have trouble with some config options 1.18.2 (.toml config file changed to .ini extension)

### ISSUE THREAD

**Issue by xFirefalconx** [MrCrayfish/Configured#122]
https://github.com/mezz/JustEnoughItems/issues/3139

Linking here (sorry I forgot) because the issue seems to stem from Configured. All data can be accessed from the above mentioned github on JEI side. (FORGE 40.2.17)
Summary:
Basically, the configs for things like column size etc don't work and it only shows serverside in configured screen. Client config is gone somehow. The file still works and can be edited with some tricks (I used FancyMenu and emulated a button that externally opens the file but eh... this is wonky and should be fixed.)

The config files for JEI have afaik changed from .toml to .ini and *that* might have caused the situation. "jei-client.ini" cannot be read as of now, anywhatsoever. 
IF you need additional info please let me know, I hope next time I won't forget the issue for months again *scratches head* 

If there's nothing you can do I guess the ugly button has to stay but at least I can still tweak my configs then. Hope that's not the case though.

**Comment by MrCrayfish** [comment]
Unfortunately it's not possible to resolve this in Minecraft 1.18.2. JEI changed to their own config system, and only in Minecraft 1.19.X and above of JEI were changes made to make it possible to integrate with Configured.
