### ISSUE TITLE
Version 1.20.1 can't properly identify config files

### ISSUE THREAD

**Issue by Kiyo-Chan** [MrCrayfish/Configured#125]
When I click a specific mod config, it is always directed to a mixed, incomplete config panel.
![QQ截图20240216205402](https://github.com/MrCrayfish/Configured/assets/68940685/60abeb89-cf9e-4080-985b-952aab9a1dde)

**Comment by MrCrayfish** [comment]
Update to the latest version

**Comment by Kiyo-Chan** [comment]
Can you update the 1.20.1 version to 2.2.3, where I noticed you've fixed that bug.
I can't update my MC version, sorry :( , or I may lose most of my mods.

**Comment by Kiyo-Chan** [comment]
> Update to the latest version

Can you update the 1.20.1 version to 2.2.3, where I noticed you've fixed that bug.
I can't update my MC version, sorry :( , or I may lose most of my mods.

**Comment by 2el222** [comment]
why would u update 1.20.4 but not 1.20.1 ? is there some kind of logic behind that?
