### ISSUE TITLE
crash on launch 1.20.1 Fabric

### ISSUE THREAD

**Issue by szunakabeats** [MrCrayfish/Configured#129]
![image](https://github.com/MrCrayfish/Configured/assets/88375166/23418ae0-2629-4acd-ae9c-2ee365dc6038)

**Comment by szunakabeats** [comment]
and yes there is no framework 0.6.27

![image](https://github.com/MrCrayfish/Configured/assets/88375166/8dff2090-dadb-431a-9cfc-e1bd0c1af26d)

**Comment by davidromrell** [comment]
it is there on a different page non-fabric version,  it still malfunctions so you will need to use a lower version of configured and 0.6.26 framework

**Comment by MrCrayfish** [comment]
Framework 0.6.27 is available.
