### ISSUE TITLE
How do I even open the Configuration menu on 1.20.1?

### ISSUE THREAD

**Issue by DrCookie95** [MrCrayfish/Configured#137]
I play on Fabric 1.20.1, and the absence of the "Mods" button on the main menu makes it impossible for me to actually know how to open the configuration menu

**Comment by NoHaxJustFlying** [comment]
I'm also having the same issue. It seems like a bug atm with 1.20.1. Does anyone know any other configuration mods?

**Comment by MrCrayfish** [comment]
You will need to install a mod like Catalogue or Mod Menu to access configurations. Fabric doesn't have a mod list screen like Forge/NeoForge.
