### ISSUE TITLE
Crash when saving new configuration on Minecraft 1.21 / Neoforge 21.0.61 beta

### ISSUE THREAD

**Issue by VusyBery** [MrCrayfish/Configured#147]
On version specified in title, game crashes when clicking on "Save" after changing the config of the a mod. Config is still succesfully changed to the new configuration upon restarting the game.

Crash report :
[crash-2024-07-07_23.19.49-client.txt](https://github.com/user-attachments/files/16133553/crash-2024-07-07_23.19.49-client.txt)

**Comment by MrCrayfish** [comment]
Update to 1.21.1 and download latest version of Configured
