### ISSUE TITLE
[1.21] [Neoforge] Crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [MrCrayfish/Configured#148]
Log: https://pastebin.com/PdMvWeFE
configured-neoforge-1.21-2.5.0.jar
Neoforge: 21.0.86
![image](https://github.com/user-attachments/assets/de24f496-a8d5-4769-a0b9-002cea461366)

**Comment by LegitGamer1017** [comment]
I get the same error and my logs look pretty similar.

**Comment by ffuentesm** [comment]
the `config` directory is used for the default configuration (NeoForge)
The is no more  `nightconfig`

**Comment by NovaViper** [comment]
Can confirm the same bug on 1.21 aswell, with included logs: https://mclo.gs/qPkySAT

**Comment by magcicada** [comment]
Just because the code of NightConfig update for [this change](https://github.com/neoforged/NeoForge/commit/4c4b8a5fef79976c8b857ea5f6bbeb741e4b0e60)

**Comment by MokahTGS** [comment]
Yup, 1.21 crash

https://pastebin.com/ZfR0YgGm

**Comment by SeptJack** [comment]
same exact thing, dont wanna switch to forge either cuz i use mods that are on neoforge but not forge
edit: found a work around for now switch to neoforge v21.0.81, not fully tested yet but its gotten me ingame
most mods no longer work on this older neoforge version so even tho it fixes the issue with configured it causes incompatibilities with most other mods

**Comment by MrCrayfish** [comment]
I'll have a fix out soon. NeoForge made some changes to their config system.

**Comment by SeptJack** [comment]
> I'll have a fix out soon. NeoForge made some changes to their config system.

when's soon?

**Comment by moon-st0ne** [comment]
still happening, hopefully gets fixed soon.

**Comment by Tapacywka** [comment]
Any updates?

**Comment by penturt** [comment]
any update in this issue, its still happening.

**Comment by Enderteck** [comment]
Hi happens to me too, are there any alternatives to configured I can use in the meantime ?

**Comment by alexks02** [comment]
Hello there :-) Any updates?

**Comment by Canpake59** [comment]
Still happening :(

**Comment by awesomeshot5051** [comment]
Give the man a break. I don't think you realize how hard it is to deal with Minecraft Modding. Minecraft isn't built by default to be modded, even though Microsoft says it is. And Neoforge is still trying to iron out it's own bugs. It's a pain in the butt all the way around. The issue was opened in July. Give him a chance to look at the error and debug, which takes awhile. And depending on the amount of time you have available dedicated to modding, you might not have time to sit down and do an extensive Debugging session. Sheesh.

**Comment by MrCrayfish** [comment]
Just letting everyone know in the thread that I haven't forgotten about this. While rewriting the NeoForge config implementation, I've had to update the API to accommodate these new changes. This has unfortunately has taken longer than expected. Good news though is that the update should be out by the weekend.

**Comment by MrCrayfish** [comment]
The update is now available, and I am assuming most have moved to 1.21.1 since the date of the original report. You should adopt to 1.21.1 if you are still on 1.21.

**Comment by NovaViper** [comment]
Can confirm it works on 1.21.1. Thank you @MrCrayfish !

**Comment by Big-GGG** [comment]
Happend again same problem with 1.21.1
