### ISSUE TITLE
Ask for help with translatable config

### ISSUE THREAD

**Issue by Boshigiri** [MrCrayfish/Configured#156]
For many configs, the translations I added are recognized by the neoforge, but configured cannot get these translations.

Such as, "mod_id.configuration.key_name": "translated content" can work well without configured.
I can see the translated content in the config screen of neoforge.

With configured, there only show "key_name", no translation.

If it cannot be translated, it will be very difficult to use some large mods, many mod authors didn't add translatable options.

**Comment by MrCrayfish** [comment]
NeoForge just recently reworked their config system, so that is probably why the translations are not working for Configured.
