### ISSUE TITLE
Configured bypasses Forge's configuration validation system

### ISSUE THREAD

**Issue by FireController1847** [MrCrayfish/Configured#16]
Hey there,

I don't have much experience with Forge's validation system for configurations, but all I know is that it _does_ have one. It appears that there are no checks run when modifying a config with this mod.

See #15 for an example of how this can go wrong. If the mod somehow configures a configuration improperly, there are no safety checks to ensure that it retains the correct types. Conversely, when modifying the file during runtime or before launch, Forge runs a type-check on all configuration options and if they're invalid or cannot be parsed, resets the config.

Unsure if this is intentional or not, just wanted to report it to make you aware of it.

**Comment by MrCrayfish** [comment]
This issue has now been fixed. I was unable to test with your mod which I am sure you are aware why.

**Comment by FireController1847** [comment]
Thanks a ton, I'll be sure to do some testing on my own end once I make that fix.
