### ISSUE TITLE
Configured not working

### ISSUE THREAD

**Issue by CrazyGamer2241** [MrCrayfish/Configured#26]
I got an ingame message telling me to install the configured mod to use the ui for the JEI mod. Although after installing the configured mod i still get an ingame message telling me to install it when i try to configure JEI through the ui.

**Comment by MrCrayfish** [comment]
This is fixed in an upcoming update to JEI. The latest release available on CurseForge does not have the fix yet.
Same issue reported on JEI: https://github.com/mezz/JustEnoughItems/issues/2538
