### ISSUE TITLE
"java.util.ConcurrentModificationException: null" from Configured during FML loading on version 1.3.1

### ISSUE THREAD

**Issue by genderneutralnoun** [MrCrayfish/Configured#28]
Crash log:
[https://betterpaste.me/?d1f172a900011d3f#AvP6wcQkMhcnfoUdXRndetNBj9JhmCGv18FB578Pp8xK](https://betterpaste.me/?d1f172a900011d3f#AvP6wcQkMhcnfoUdXRndetNBj9JhmCGv18FB578Pp8xK)
Only happened after upgrading to 1.3.1 of Configured. Loaded successfully when I downgraded back to 1.3.0.

**Comment by Brycey92** [comment]
I am also experiencing this crash.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Configured/commit/df3e8ed3e00bc6d6112d342de65b6a9455af0f21 (applies to 1.16.5 and 1.17.1)

**Comment by Brycey92** [comment]
Thanks! :smile:
