### ISSUE TITLE
java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/AbstractConfigListEntry

### ISSUE THREAD

**Issue by SirKrunk** [MrCrayfish/Configured#31]
I'm using version 1.50, and I got this message
<img width="950" alt="image" src="https://user-images.githubusercontent.com/94970733/143548700-2b8a82e4-530b-494c-9d52-e5b8ca5cc07b.png">
Edit: I'm using v 1.40, gonna update now
Edit 2: v 1.50 also has this problem

**Comment by MrCrayfish** [comment]
It's Netherite Plus Mod. Update to the latest version of that mod.

**Comment by SirKrunk** [comment]
ok
