### ISSUE TITLE
NPE on configured's world select screen if a world doesn't have an icon

### ISSUE THREAD

**Issue by TJT01** [MrCrayfish/Configured#34]
The game crashes when opening the "Select World To Edit Server Config" screen if a world does not have an icon.
https://gist.github.com/TJT01/5478018c3b6fd3d6972369a6d686cf30

Minecraft: 1.16.5
Forge: 36.2.0
Configured: 1.5.1-1.16.5

**Comment by MrCrayfish** [comment]
Thanks. Fixed in https://github.com/MrCrayfish/Configured/commit/122ea29ef114030f70ab0f998aa82c83b5461e06
