### ISSUE TITLE
Nullpointer when saving config for Distant Horizons 

### ISSUE THREAD

**Issue by SettingDust** [MrCrayfish/Configured#38]
Version: configured:1.5.1-1.16.5

~~Another exception. Exception is https://github.com/MrCrayfish/Configured/issues/32 before. And throw this after update.~~
https://www.curseforge.com/minecraft/mc-mods/lod-level-of-detail
https://bytebin.lucko.me/jpi9BGNzpV

~~Edit:
They are same exception. The #32 haven't been fixed~~

Edit1:
> Not the same issue as #32 since that is related to the config reloading event. The crash report given does not mention this.

**Comment by MrCrayfish** [comment]
It seems I forgot to include the fix from the 1.16 version into 1.18. I will release a patch soon

**Comment by SettingDust** [comment]
> 

Ah. It's 1.16. And it's another exception. Not the same as prev

**Comment by SettingDust** [comment]
> It seems I forgot to include the fix from the 1.16 version into 1.18. I will release a patch soon

Ah. They are the same exceptions. My fault. The minecraft is 1.16, not 1.18. So, it's seems that the bug isn't fixed

**Comment by MrCrayfish** [comment]
Not the same issue as #32 since that is related to the config reloading event. The crash report given does not mention this.

**Comment by MrCrayfish** [comment]
It seems that Distant Horizons is registering their config at the wrong time. It should be in the constructor of their mod class, not the common setup phase. I just confirmed this by putting my registration in the common setup and it crashed too.

**Comment by MrCrayfish** [comment]
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues

**Comment by SettingDust** [comment]
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/136
