### ISSUE TITLE
[1.16-1.18] Add Support for custom configs

### ISSUE THREAD

**Issue by Speiger** [MrCrayfish/Configured#42]
o/ Love the configured mod.

Sadly the mod I am writing right now (IC2Classic) has a custom config system.
Why? Forge format sadly sucks and doesn't support whats required.

So would you consider adding support for custom configs?
I do not mean that you should add like specific support for my mod and have like a special class just for me.
What i mean is. You are already almost using wrapper classes around everything. So why not finish the job and allow others to add their own format that way.

From what it looked like it might be a bit of work to achieve that but relatively speaking not as much as creating it from scratch.
Simply refactoring some wrapper classes and making a couple classes public.

Thanks for reading and have a nice day.

**Comment by MrCrayfish** [comment]
I'll look into it. I definitely think it's a good idea to allow support to be added through community addons. If you've got any insight on what needs to be available (in my code) to modders to achieve this, let me know as it'll be a big help.

**Comment by Speiger** [comment]
A lot of implementations use forges stuff directly.

The only classes that are really needing a refactor are IEntry (and its implementations), ValueHolder and ConfigScreen.

The simplest approach would be. Remove all the forge stuff and recreate the requirements through a custom interface that everyone could implement.

This also should improve the fabric/forge maintainablilty since you are no longer writing 2 implementations but 1 and have just 2 interface implementations.

Right now I don't have enough time to make a pullrequest... So would be nice if you could do that.

**Comment by MrCrayfish** [comment]
[Merge in faaedc92e11e8c8bf11ecc51520ae7fc92cf21fb](https://github.com/MrCrayfish/Configured/pull/44)

**Comment by Speiger** [comment]
@MrCrayfish would you add me via discord?
I have a few things i like to ask you in pm.
