### ISSUE TITLE
Crash in 1.16.5 when trying to use Configured.

### ISSUE THREAD

**Issue by HauntedSniper** [MrCrayfish/Configured#45]
I believe this was already reported, but the fix seems to have only been added to 1.18, I also tried to use an older version just to see if that may help but the same crash happened when I tried to change a config, specifically, when I tried to select the World button.

Here's the crash report in case it's necessary.
[crash.txt](https://github.com/MrCrayfish/Configured/files/8056689/crash.txt)

**Comment by MrCrayfish** [comment]
Huh. I fixed the issue just never published the patch. Check CurseForge soon.
