### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by ModernGamingWorld** [MrCrayfish/Configured#47]
I am using the new 1.18.2 version and as soon as I download it and Launched my modpack, REI stopped working and would not show up or work, but as soon as I removed Configured from my Modpack REI started to work. I have checked the logs and dont see anything weird that should be causing this

**Comment by MrCrayfish** [comment]
Send your logs

**Comment by ModernGamingWorld** [comment]
@MrCrayfish I think after you updated Catalogue it fixed itself, I added both in Configured and Now Catalogue and REI works again, so I think it might have been cause I added Configured without Catalogue
