### ISSUE TITLE
[Bug][1.16.5] String values hate special characters.

### ISSUE THREAD

**Issue by Speiger** [MrCrayfish/Configured#48]
I noticed that Configured doesn't like the repeating of certain characters.
Also side bug that I would suggest fixing:
![image](https://user-images.githubusercontent.com/2556269/166882970-31a3f973-0c90-4448-9da4-f833ab8353a7.png)
Maybe its worth implementing a dynamic constraint that provides more space if present. 

But yeah when i click on Blast Protection enchantment:
![image](https://user-images.githubusercontent.com/2556269/166883106-2a715fbc-b212-4b94-8c3c-60025e205ddb.png)
You see it removes a lot of characters that should be present.

Yes the ;;; is intentional because it is used with string.split(";") and java actually turns the entry into a null or empty string.

And since I saw you worked on this why not show this issue found a couple weeks ago.

Also small thank you for making this mod so simple to understand, helped me out with my game engine, where I want to have something like this directly implemented.

**Comment by MrCrayfish** [comment]
This shouldn't happen since e2b4ede033bf61db3ecf652e0bd21eb530a03e25 fixed the issue.
Tested myself and seems to be fine.
![image](https://user-images.githubusercontent.com/4958241/166886729-f163e73b-77e5-45f3-8083-ae7309b41849.png)

**Comment by Speiger** [comment]
Ahhh yeah it could be that i have a outdated version in my IDE. I tend to do that. Thank you ^^"
