### ISSUE TITLE
[Feature request] Save/load changes

### ISSUE THREAD

**Issue by Lolcroc** [MrCrayfish/Configured#58]
Not sure if this fits in the design of the mod, but it would be nice to save or load all changes to configuration files (i.e. away from defaults) as a file of some kind. This way I can track my entire configuration somewhere on my PC between modpacks or when sharing with friends.
If interested I can also try to write something and make a pull request, let me know. Much love xoxo

**Comment by MrCrayfish** [comment]
I can definitely add an option to show which config values have been changed in the menu (e.g. highlighted names). If you can more clearly describe your use case then I may understand better what is needed. From my perspective you can visually see if a value is different by comparing it to the default value specified in the comment.

**Comment by Lolcroc** [comment]
Never mind!

I originally intended for easy saving and loading of config values, because sometimes on some set of mods I have many small changes in various config files that are impossible to remember. If I am transitioning to a new MC version or different mod pack I need to manually copy over those settings, because custom launchers keep those files in distinct locations. However I found that Forge is able to autocomplete outdated or partially filled configuration files, so my feature request can simply be done by copy-pasting the entire config folder between different MC distributions. This is not very pretty but it works fine.
