### ISSUE TITLE
minecraft crashed if i select a world config??

### ISSUE THREAD

**Issue by Tom28281** [MrCrayfish/Configured#66]
so i was playing a modpack i made in 1.19 with project mmo, i go to configure some things but every setting that has the "select world" crashes when i click it. why is this happening???

**Comment by MrCrayfish** [comment]
What version are you using?

**Comment by Tom28281** [comment]
1.19 and version 1.5.5

**Comment by MrCrayfish** [comment]
Update to the latest version...
