### ISSUE TITLE
Suggestion: Alphabetical sort by default

### ISSUE THREAD

**Issue by mimi-min** [MrCrayfish/Configured#67]
Exactly what it says on the tin :)

I already select it every time anyway, why not have it selected by default?

**Comment by MrCrayfish** [comment]
It already is
![image](https://user-images.githubusercontent.com/4958241/183896697-bb3f8f88-edde-4474-85b2-3c408d3c8fe2.png)

**Comment by mimi-min** [comment]
Oh, I meant the mod list... is that still part of configured though? Maybe it's not...

**Comment by MrCrayfish** [comment]
If talking about Catalogue, it is too!
![image](https://user-images.githubusercontent.com/4958241/185134534-84266739-52f9-40a3-a2f1-cef91526c478.png)
