### ISSUE TITLE
[1.18.2] Kind of rare crash when launching modpack.

### ISSUE THREAD

**Issue by Gbergz** [MrCrayfish/Configured#71]
Title^
Users in my modpack experiences crashes when starting modpack.
This is not for everbody and it might not even be caused by Configured, but it has been reported a few times now and it says something with Configured so I'm gonna give it a shot and report it here.

**Minecraft:** 1.18.2
**Forge:** 40.1.73
**Configured:** 1.5.4 | https://www.curseforge.com/minecraft/mc-mods/configured/files/3946495

**Crash-Report:** https://gist.github.com/Gbergz/62d8378a52428221517020c285883229

Edit: User removed the mod Oculus and now the game boots. Something that wasn't a problem before, but I guess it not might bcs of this mod but is on Oculus side instead.

Edit 2: Got more reports of it happening without Oculus so it might not be that.

**Comment by falxie** [comment]
I wouldn't chock it up to Oculus. I've been having the same intermittent crashes that point to Configured as well

**Comment by drakray** [comment]
https://pastebin.com/n1rbExUR
Got the same thing after updating Caupona, IDAS, Minecolonies
Sophisticated Core/Backpack/Storage, and adding LibraryFerret, Better Village and Awesome Dungeon+Ocean/Nether/End addons

**Comment by MokahTGS** [comment]
Seeing this crash as well:  https://pastebin.com/msp8dMk7

**Comment by mertgoksel** [comment]
Same crash, dont have oculus. https://pastebin.com/1wDM2TVN

**Comment by MrCrayfish** [comment]
Fixed using 2.0.0
