### ISSUE TITLE
1.19.2 Iceberg only supports configured 2.0.0 or above versions 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MrCrayfish/Configured#72]
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.1.28-universal.jar%23392!/:?] {re:classloading}
-- MOD iceberg --
Details:
	Mod File: /M:/Minecraft/Curseforge/Instances/1.19.2-Fiction Friction SP/mods/Iceberg-1.19.2-forge-1.0.47.jar
	Failure message: Mod iceberg only supports configured 2.0.0 or above
		Currently, configured is 1.5.8
	Mod Version: 1.0.47
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by P3rf3ctXZer0** [comment]
I saw this https://github.com/AHilyard/Iceberg/issues/11

**Comment by AHilyard** [comment]
@P3rf3ctXZer0 Just so you're aware, this issue is fixed in Iceberg version 1.0.48.  Configured 1.x support was removed, but it will no longer prevent your game from loading if your installed version is less than 2.0.
