### ISSUE TITLE
configured.developer.toml file wipes

### ISSUE THREAD

**Issue by DrFiishy** [MrCrayfish/Configured#77]
So whenever i want to just enable it or enter a UUID it just wipes the file and puts it back to ''factory settings'', tried making it read only but then crashes the server instantly.

**Comment by MrCrayfish** [comment]
If you don't write the correct syntax, the file resets.
UUID should be inside quotes.

**Comment by Ryonez** [comment]
It would be good to note this in the config file.

**Comment by Xiarno** [comment]
~~@MrCrayfish What is the correct syntax? I've been trying to find it for a while without success.~~
Nevermind I'm dumb.
