### ISSUE TITLE
[1.16.5] Text spacing for some mods is illlegible

### ISSUE THREAD

**Issue by CactusDuud** [MrCrayfish/Configured#8]
![image](https://user-images.githubusercontent.com/39608466/118377104-abefe880-b580-11eb-9cc2-5549160e5e4b.png)

Not sure if this can be helped, but I can't read the config option or its value :(

**Comment by MrCrayfish** [comment]
The longer text drawing over the buttons is an issue but the mod you're looking at hasn't provided translations for their config options.

**Comment by Mackzwellz** [comment]
> The longer text drawing over the buttons is an issue

More info in https://github.com/MrCrayfish/Catalogue/issues/3 . I assume this issue will be used to fix this, so linking it here.

**Comment by MrCrayfish** [comment]
Fixed names drawing over elements in https://github.com/MrCrayfish/Configured/commit/0f38879e3b71c818723b8117c13a7bb4c7a19a39 and translations are now only used if they are actually present in a lang json, in https://github.com/MrCrayfish/Configured/commit/633879412ca3ea4452a15df155ef1c7dbb61cc89
