### ISSUE TITLE
homepage down

### ISSUE THREAD

**Issue by Speiger** [MrCrayfish/Configured#81]
Just randomly looked at the mods list and configured url showed up and i thought. "Hmmm lets look how the project is going"
Clicked the link and the page is down.

https://mrcrayfish.com/mods?id=configured

**Comment by MrCrayfish** [comment]
Already aware. Don't use GitHub to report issue for my website.

**Comment by Speiger** [comment]
Dont really have a other way to contact you so took that. ^^
