### ISSUE TITLE
1.19.2: Simple Text Overlay doesn't require an update

### ISSUE THREAD

**Issue by Daltaxy** [MrCrayfish/Configured#87]
Hello. This is a really minor issue, and you can go ahead and close this if you don't care, it's fine.
On 1.19.2 at least, on Configured 2.0.1, it has been a while since I've first seen that in the mods section, Simple Text Overlay is considered to have an update. Of course, it doesn't have an update though.
![image](https://user-images.githubusercontent.com/111076631/223184880-5e65379c-f486-47c0-a554-f85d2eb629c6.png)
![image](https://user-images.githubusercontent.com/111076631/223185100-a2539968-0336-4a62-8587-9b44cfedbb0c.png)
thank you for your attention

**Comment by MrCrayfish** [comment]
I don't control if a mod needs an update, that is the Forge Update Checker.
