### ISSUE TITLE
Error during loading mods.

### ISSUE THREAD

**Issue by AL3XIVS** [MrCrayfish/Configured#9]
Info: MC 1.16.5 / Forge 36.1.18 / Configured 0.4.2

I don't know why this error is happening now, but for what i'm understanding its an error about Cloth Config API, i had the mod earlier but now i deleted it because i don't need it anymore but in the dependecies of Configured there isn't any need of it.
![2021-05-16_04 19 23](https://user-images.githubusercontent.com/83294912/118383556-1e9fa900-b5ff-11eb-8a44-a472fdcefb0b.png)

**Comment by MrCrayfish** [comment]
Can you send the crash log? I'm not sure why this would be crashing.

**Comment by AL3XIVS** [comment]
I don't know either but if i can help finding the problem im at your service.
[crash-2021-05-16_04.19.10-fml.txt](https://github.com/MrCrayfish/Configured/files/6489345/crash-2021-05-16_04.19.10-fml.txt)

**Comment by MrCrayfish** [comment]
Crash seems to point to Netherite Plus Mod

**Comment by AL3XIVS** [comment]
Well, you seem to be right, i tried to launch without it and it loads normally, then if you think its a problem on their end i can report this crash to them.
The thing i don't understand remain why this crash happens only now, i already played with them paired together.

**Comment by MrCrayfish** [comment]
Are you playing with a modpack authored by someone else? If so, it may have updated. If I am correct, the game should crash if you try to access Netherite Plus Mod config menu through the mod list. Can you try this without Configured installed?

**Comment by AL3XIVS** [comment]
So i'm not playing using any modpack, those are all mods i've chosen from myself, the game crashes directly on startup not when i try to access config file using Configured, and it launches correctly removing Configured and viceversa, i always try to keep mods updated so yeah.
I used to modify config files directly from the folder with notepad then i started using Configured and if the mod isn't compatible with Configured i still do it from the folder.
Do you need my mods list?

**Comment by MrCrayfish** [comment]
So I tested this myself, it looks like you need to install Cloth Config API. https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge
It's seem like an issue to do with either Netherite Plus Mod or it's parent mod Architectury API. From my understanding, they don't correctly handle optional dependencies and try to load code from a mod that doesn't exist, eg Cloth Config API.
