### ISSUE TITLE
CONFIGURED stopped working; out of 600 or so mods only a few have a useable config button. The rest are all greyed out.

### ISSUE THREAD

**Issue by Minebrah** [MrCrayfish/Configured#90]
I've been using CONFIGURED for a long time now and its always worked fine. But recently I went through and Updated forge from 43.1.52 to 43.2.6, as well as updated a bunch of other mods, and it just stopped working. This is my debug, if you need any other info let me know. I love this mod and would really like to get it working again.

[debug.log](https://github.com/MrCrayfish/Configured/files/11033905/debug.log)

**Comment by MrCrayfish** [comment]
Fixed now. Download the latest update.

**Comment by Minebrah** [comment]
IT WORKS!! THANK YOU SO MUCH MAN. I SINCERELY APPERCIATE IT.
